# Generated by Django 5.2.7 on 2025-10-27 09:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_type', models.CharField(choices=[('mothers_union', "Mother's Union"), ('kama', 'KAMA - Men Ministry'), ('youth', 'Youth Ministry'), ('children', 'Children Ministry'), ('choir', 'Choir & Worship'), ('other', 'Other')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('message', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('contact_notes', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Interest Form Submissions',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ministry_type', models.CharField(choices=[('youth', 'Youth Ministry'), ('children', 'Children Ministry'), ('women', "Mother's Union"), ('men', 'KAMA - Men Ministry'), ('choir', 'Choir & Worship Ministry'), ('other', 'Other Ministry')], max_length=20)),
                ('description', models.TextField()),
                ('leader_name', models.CharField(blank=True, max_length=100)),
                ('leader_email', models.EmailField(blank=True, max_length=254)),
                ('leader_phone', models.CharField(blank=True, max_length=15)),
                ('meeting_schedule', models.TextField(help_text='Regular meeting days and times')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ministries.ministry')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MinistryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ministries/gallery/')),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ministries.ministry')),
            ],
            options={
                'verbose_name_plural': 'Ministry Galleries',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('day_of_week', models.CharField(blank=True, max_length=20)),
                ('time', models.CharField(help_text='e.g., Sundays, 9:30-10:30am', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('target_audience', models.CharField(blank=True, max_length=100)),
                ('is_recurring', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='Weekly', help_text='e.g., Weekly, Monthly, Bi-weekly', max_length=50)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='ministries.ministry')),
            ],
            options={
                'ordering': ['ministry', 'day_of_week', 'time'],
            },
        ),
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254...'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('assistant_leader', 'Assistant Leader'), ('member', 'Member'), ('volunteer', 'Volunteer')], default='member', max_length=20)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ministries.ministry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ministry', 'role', 'full_name'],
                'unique_together': {('email', 'ministry')},
            },
        ),
    ]
