# Generated by Django 4.2.25 on 2025-11-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_parentresource_parentsubscription_weeklyprogram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentResource',
            new_name='VisitorResource',
        ),
    ]
