# Generated by Django 4.2.25 on 2025-11-04 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0003_rename_parentresource_visitorresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentSubscription',
        ),
        migrations.AlterField(
            model_name='visitorresource',
            name='file',
            field=models.FileField(upload_to='visitor_resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
