# Generated by Django 4.2.25 on 2025-11-04 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0004_delete_parentsubscription_alter_visitorresource_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MothersUnionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(help_text='Font Awesome icon class (e.g., fas fa-praying-hands)', max_length=100)),
                ('description', models.TextField()),
                ('schedule', models.CharField(blank=True, help_text='e.g., Every Wednesday, 2:00 PM', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'verbose_name_plural': 'Mothers Union Activities',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MothersUnionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mothers Union Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MothersUnionLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mothers_union/leaders/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MothersUnionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mothers Union Memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
