# Generated by Django 4.2.25 on 2025-11-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0005_mothersunionactivity_mothersunionevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(help_text='Font Awesome icon class (e.g., fas fa-calendar-alt)', max_length=100)),
                ('schedule', models.CharField(blank=True, help_text='e.g., Every 1st Saturday, 9:00 AM', max_length=100, null=True)),
                ('description', models.TextField(help_text='Main description of the activity')),
                ('additional_info', models.TextField(blank=True, help_text='Additional details or bullet points', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'verbose_name_plural': 'KAMA Activities',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KamaLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='kama/leaders/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'KAMA Leaders',
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='KamaMotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.TextField(help_text="KAMA motto e.g., 'Men of Faith, Men of Action, Men of Service'")),
                ('description', models.TextField(blank=True, help_text='Optional description of the motto')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'KAMA Motto',
            },
        ),
    ]
