# Generated by Django 4.2.25 on 2025-11-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0006_kamaactivity_kamaleader_kamamotto'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamaMembershipInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(help_text='Why they want to join KAMA')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
            ],
            options={
                'verbose_name_plural': 'KAMA Membership Interests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
