# Generated by Django 4.2.25 on 2025-11-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0007_kamamembershipinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestformsubmission',
            options={'ordering': ['-submission_date'], 'verbose_name_plural': 'KAMA Form Submissions'},
        ),
    ]
