# Generated by Django 4.2.25 on 2025-11-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0008_alter_interestformsubmission_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KamaMembershipInterest',
        ),
        migrations.AlterModelOptions(
            name='interestformsubmission',
            options={'ordering': ['-submission_date'], 'verbose_name_plural': 'KAMA Membership Interest'},
        ),
    ]
