# Generated by Django 4.2.25 on 2025-11-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0009_delete_kamamembershipinterest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinistryGallery',
        ),
    ]
