# Generated by Django 4.2.25 on 2025-11-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0010_delete_ministrygallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundaySchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(choices=[('why_join', 'Why Join Us'), ('requirements', 'Requirements')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sunday School Information',
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_age', models.IntegerField()),
                ('age_group', models.CharField(choices=[('nursery', 'Nursery (3-5 years)'), ('primary', 'Primary (6-9 years)'), ('juniors', 'Juniors (10-12 years)')], max_length=20)),
                ('parent_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('regular', 'Regular Sunday Schedule'), ('special', 'Special Activities')], max_length=20)),
                ('title', models.CharField(help_text='e.g., Sunday Schedule, Special Activities', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sunday School Schedules',
                'ordering': ['order', 'schedule_type'],
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='e.g., Nursery Class Teacher', max_length=100)),
                ('age_group', models.CharField(choices=[('nursery', 'Nursery (3-5 years)'), ('primary', 'Primary (6-9 years)'), ('juniors', 'Juniors (10-12 years)')], max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sunday_school/teachers/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'age_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='e.g., 9:00 AM, 1st Sunday, Monthly', max_length=100)),
                ('activity', models.CharField(help_text='e.g., Arrival & Welcome, Family Service', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('order', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ministries.sundayschoolschedule')),
            ],
            options={
                'ordering': ['schedule', 'order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ministries.sundayschoolinfo')),
            ],
            options={
                'ordering': ['info', 'order'],
            },
        ),
    ]
