# Generated by Django 4.2.25 on 2025-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0011_sundayschoolinfo_sundayschoolregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMinistryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('team', models.CharField(choices=[('choir', 'Choir Team'), ('praise', 'Praise & Worship Team'), ('both', 'Both Teams')], max_length=20)),
                ('experience', models.CharField(choices=[('none', 'No formal experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], max_length=20)),
                ('instrument', models.CharField(choices=[('soprano', 'Soprano (Choir)'), ('alto', 'Alto (Choir)'), ('tenor', 'Tenor (Choir)'), ('bass', 'Bass (Choir)'), ('guitar', 'Guitar'), ('piano', 'Piano/Keyboard'), ('drums', 'Drums'), ('bass_guitar', 'Bass Guitar'), ('other', 'Other Instrument')], max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MusicMinistryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_type', models.CharField(choices=[('choir', 'Choir Team'), ('praise', 'Praise & Worship Team'), ('both', 'Both Teams')], max_length=20)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-microphone-alt', max_length=50)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
