# Generated by Django 4.2.25 on 2025-11-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0012_musicministryregistration_musicministryteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicministryteam',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='musicministryteam',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='musicministryteam',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='musicministryteam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musicministryteam',
            name='leader_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
