# Generated by Django 4.2.25 on 2025-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0013_remove_musicministryteam_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicministryteam',
            name='icon_class',
            field=models.CharField(default='fas fa-microphone-alt', max_length=50),
        ),
        migrations.AddField(
            model_name='musicministryteam',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicministryteam',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicministryteam',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='musicministryteam',
            name='leader_phone',
            field=models.CharField(max_length=20),
        ),
    ]
