# Generated by Django 4.2.25 on 2025-11-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0014_musicministryteam_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyprogram',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Youth Weekly Programs'},
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='program_type',
            field=models.CharField(choices=[('youth_bonding', 'Team Bonding'), ('youth_night', 'Youth Night Kesha'), ('small_groups', 'Small Team Building'), ('Bible_Study', 'Bible Study'), ('other', 'Other')], max_length=20),
        ),
    ]
