# Generated by Django 4.2.25 on 2025-11-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0015_alter_weeklyprogram_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
