# Generated by Django 4.2.25 on 2025-10-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0002_alter_event_options_alter_sermon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('DIOCESE', 'Diocese Leader'), ('VICAR', 'Vicar'), ('ASSISTANT_VICAR', 'Assistant Vicar'), ('YOUTH_LEADER', 'Youth Ministry Leader'), ('MU_LEADER', 'Mothers Union Leader'), ('KAMA_LEADER', 'KAMA Leader'), ('SUNDAY_SCHOOL_LEADER', 'Sunday School Leader'), ('CHOIR_LEADER', 'Choir/Worship Leader'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('ELDER', 'Church Elder')], max_length=50)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'position', 'name'],
            },
        ),
    ]
