# Generated by Django 4.2.25 on 2025-11-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0003_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Link to TikTok video of this event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Link to YouTube video of this event', null=True),
        ),
    ]
