# Generated by Django 4.2.25 on 2025-11-01 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0004_event_tiktok_url_event_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('SERVICES', 'Sunday Services'), ('EVENTS', 'Special Events'), ('OUTREACH', 'Community Outreach'), ('YOUTH', 'Youth Ministry'), ('WEDDING', 'Weddings'), ('REVIVAL', 'Revivals'), ('FELLOWSHIP', 'Fellowships')], default='EVENTS', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the photo was taken')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
