# Generated by Django 4.2.25 on 2025-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0006_event_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('REVIVAL', 'Revival'), ('FELLOWSHIP', 'Fellowship'), ('WEDDING', 'Wedding'), ('PRAYER', 'Prayer Meeting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
