# Generated by Django 4.2.25 on 2025-11-03 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0007_alter_event_options_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('REVIVAL', 'Revival'), ('FELLOWSHIP', 'Fellowship'), ('WEDDING', 'Wedding'), ('PRAYER', 'Prayer')], default='FELLOWSHIP', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Link to TikTok video of this event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Link to YouTube video of this event', null=True),
        ),
    ]
