# Generated by Django 4.2.25 on 2025-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0008_alter_event_options_event_time_alter_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('kiswahili', 'Kiswahili Service'), ('english', 'English Service'), ('youth', 'Youth Service'), ('children', 'Children Service'), ('prayer', 'Prayer Service')], max_length=20)),
                ('schedule', models.CharField(help_text='e.g., Sundays at 8:00 AM', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading', null=True)),
                ('youtube_playlist_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Church Sermon Services',
                'ordering': ['order', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='SermonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('easter', 'Easter Celebration'), ('christmas', 'Christmas Service'), ('baptism', 'Baptism Service'), ('conference', 'Conference'), ('revival', 'Revival Meeting'), ('other', 'Other Event')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sermon_events/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading', null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sermon Events',
                'ordering': ['-event_date', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name_plural': 'Church Homepage Events update'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name_plural': 'Church Gallery'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['order', 'position', 'name'], 'verbose_name_plural': 'ALL CHURCH LEADERS'},
        ),
    ]
