# Generated by Django 4.2.25 on 2025-11-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0009_churchservice_sermonevent_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchservice',
            name='auto_generate_events',
            field=models.BooleanField(default=True, help_text='Automatically create past events from services'),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Date of the last service (auto-updated)', null=True),
        ),
        migrations.AddField(
            model_name='sermonevent',
            name='source_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='ack.churchservice'),
        ),
        migrations.AlterField(
            model_name='sermonevent',
            name='event_type',
            field=models.CharField(choices=[('easter', 'Easter Celebration'), ('christmas', 'Christmas Service'), ('baptism', 'Baptism Service'), ('conference', 'Conference'), ('revival', 'Revival Meeting'), ('other', 'Other Event'), ('service', 'Regular Service')], max_length=20),
        ),
    ]
