# Generated by Django 4.2.25 on 2025-11-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0010_churchservice_auto_generate_events_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchservice',
            options={'ordering': ['order', 'service_type'], 'verbose_name_plural': 'Sermon Services'},
        ),
        migrations.AlterModelOptions(
            name='sermonevent',
            options={'ordering': ['-event_date', 'order'], 'verbose_name_plural': 'Update Past Sermons'},
        ),
    ]
