# Generated by Django 4.2.25 on 2025-11-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0011_alter_churchservice_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sermon',
        ),
    ]
