# Generated by Django 4.2.25 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='offline_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
