# Generated by Django 4.2.25 on 2025-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0014_contactmessage_offline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
