# Generated by Django 4.2.25 on 2025-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0015_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_events/'),
        ),
    ]
