# Generated by Django 4.2.25 on 2025-11-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0016_alter_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
