# Generated by Django 4.2.25 on 2025-11-21 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0017_delete_contactmessage_remove_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Message Subject')),
                ('message', models.TextField(verbose_name='Review Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Received At')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], default='unread', max_length=10, verbose_name='Review Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
