# Generated by Django 4.2.25 on 2025-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ack', '0018_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event image', null=True, upload_to='events/'),
        ),
    ]
